import { OnInit, TemplateRef, EventEmitter, AfterViewInit, ElementRef, OnChanges, Renderer2 } from '@angular/core';
import { WidgetActionType } from '../core/enums/widget-action-type.enum';
import { UtilService } from '../core/services/util.service';
import * as i0 from "@angular/core";
export declare class CmacsKpiGroupComponent implements OnInit, AfterViewInit, OnChanges {
    private renderer;
    private elementRef;
    private utilService;
    columnTemplate: TemplateRef<{}>;
    canvasRef: ElementRef;
    legendContent: ElementRef<any>;
    clickMenu: EventEmitter<any>;
    headerText: string;
    footerText: string;
    footerValue: string;
    view: number[];
    data: any[];
    columnsHeader: string[];
    displayArrowBtns: boolean;
    chartWidth: number;
    fontChartNumber: number;
    col2: number;
    col3: number;
    minWidth: number;
    showChart: boolean;
    scrollY: number;
    p: number;
    scroll: {
        x: string;
        y: string;
    };
    dataTable: any[];
    configurationExpandableRows: any;
    loading: boolean;
    selectedItem: string;
    constructor(renderer: Renderer2, elementRef: ElementRef, utilService: UtilService);
    ngOnInit(): void;
    ngOnChanges(): void;
    ngAfterViewInit(): void;
    resize(): void;
    setScroll(): void;
    scrollRight(): void;
    scrollLeft(): void;
    drawCanvas(): void;
    drawPieSlice(ctx: CanvasRenderingContext2D, centerX: number, centerY: number, radius: number, startAngle: number, endAngle: number, color: any, lineWidth: number): void;
    getTotalCateg(data: any[]): number;
    setConfiguration(): void;
    setData(): void;
    getChildren(items: any[]): any[];
    menuClick(type: WidgetActionType): void;
    changeData(key: string): void;
    showArrowBtns(): void;
    getDataTable(): any[];
    getConfiguration(): any;
    getChartImage(): any;
    static ɵfac: i0.ɵɵFactoryDeclaration<CmacsKpiGroupComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CmacsKpiGroupComponent, "cmacs-kpi-group", never, { "headerText": { "alias": "headerText"; "required": false; }; "footerText": { "alias": "footerText"; "required": false; }; "footerValue": { "alias": "footerValue"; "required": false; }; "view": { "alias": "view"; "required": false; }; "data": { "alias": "data"; "required": false; }; "columnsHeader": { "alias": "columnsHeader"; "required": false; }; }, { "clickMenu": "clickMenu"; }, never, never, false, never>;
}
//# sourceMappingURL=cmacs-kpi-group.component.d.ts.map