import { EventEmitter, ChangeDetectorRef } from '@angular/core';
import { CmacsSelectComponent } from '../cmacs-select/cmacs-select.component';
import { UntypedFormGroup, UntypedFormBuilder } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class CmacsUserDropdownComponent {
    private cdr;
    private fb;
    mode: string;
    emailErrorLabel: string;
    inviteGuestLabel: string;
    loadingLabel: string;
    placeHolder: string;
    selectedValue: any;
    maxTagCount: any;
    serverSearch: boolean;
    selectedValueChange: EventEmitter<any>;
    onAddGuestUserByEmail: EventEmitter<any>;
    cmacsOnSearch: EventEmitter<any>;
    _isLoading: boolean;
    _inviteGuest: boolean;
    _searchValue: string;
    _listOfOption: any[];
    showEmailError: boolean;
    selectComponent: CmacsSelectComponent;
    listOfFilteredOption: any[];
    listDividers: any[];
    operatedData: any[];
    firstElemByDivider: any;
    emailForm: UntypedFormGroup;
    highlightKeys: any[];
    set isLoading(value: boolean);
    set inviteGuest(value: boolean);
    set listOfOption(value: any[]);
    get listOfOption(): any[];
    constructor(cdr: ChangeDetectorRef, fb: UntypedFormBuilder);
    onSelectedValueChange($event: any): void;
    get searchValue(): string;
    operateData(): void;
    onsearch($event: any): void;
    getFirstElemByDivider(): void;
    getInitials(name: any): any;
    getSafeImage(picture: any): any;
    onError(elem: any): void;
    addGuestUser(): void;
    addOption(option: any): void;
    removeOption(option: any): void;
    highlightValue(elem: any): any[];
    static ɵfac: i0.ɵɵFactoryDeclaration<CmacsUserDropdownComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CmacsUserDropdownComponent, "cmacs-user-dropdown", ["cmacsUserDropdown"], { "mode": { "alias": "mode"; "required": false; }; "emailErrorLabel": { "alias": "emailErrorLabel"; "required": false; }; "inviteGuestLabel": { "alias": "inviteGuestLabel"; "required": false; }; "loadingLabel": { "alias": "loadingLabel"; "required": false; }; "placeHolder": { "alias": "placeHolder"; "required": false; }; "selectedValue": { "alias": "selectedValue"; "required": false; }; "maxTagCount": { "alias": "maxTagCount"; "required": false; }; "serverSearch": { "alias": "serverSearch"; "required": false; }; "isLoading": { "alias": "isLoading"; "required": false; }; "inviteGuest": { "alias": "inviteGuest"; "required": false; }; "listOfOption": { "alias": "listOfOption"; "required": false; }; }, { "selectedValueChange": "selectedValueChange"; "onAddGuestUserByEmail": "onAddGuestUserByEmail"; "cmacsOnSearch": "cmacsOnSearch"; }, never, never, false, never>;
}
//# sourceMappingURL=cmacs-user-dropdown.component.d.ts.map