import { EventEmitter, ChangeDetectorRef } from '@angular/core';
import { CmacsSelectComponent } from '../cmacs-select/cmacs-select.component';
import { FormGroup, FormBuilder } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class CmacsUserDropdownComponent {
    private cdr;
    private fb;
    mode: string;
    emailErrorLabel: string;
    inviteGuestLabel: string;
    loadingLabel: string;
    placeHolder: string;
    selectedValue: any;
    maxTagCount: any;
    serverSearch: boolean;
    selectedValueChange: EventEmitter<any>;
    onAddGuestUserByEmail: EventEmitter<any>;
    cmacsOnSearch: EventEmitter<any>;
    _isLoading: boolean;
    _inviteGuest: boolean;
    _searchValue: string;
    _listOfOption: any[];
    showEmailError: boolean;
    selectComponent: CmacsSelectComponent;
    listOfFilteredOption: any[];
    listDividers: any[];
    operatedData: any[];
    firstElemByDivider: any;
    emailForm: FormGroup;
    highlightKeys: any[];
    set isLoading(value: boolean);
    set inviteGuest(value: boolean);
    set listOfOption(value: any[]);
    get listOfOption(): any[];
    constructor(cdr: ChangeDetectorRef, fb: FormBuilder);
    onSelectedValueChange($event: any): void;
    get searchValue(): string;
    operateData(): void;
    onsearch($event: any): void;
    getFirstElemByDivider(): void;
    getInitials(name: any): any;
    getSafeImage(picture: any): any;
    onError(elem: any): void;
    addGuestUser(): void;
    addOption(option: any): void;
    removeOption(option: any): void;
    highlightValue(elem: any): any[];
    static ɵfac: i0.ɵɵFactoryDef<CmacsUserDropdownComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<CmacsUserDropdownComponent, "cmacs-user-dropdown", ["cmacsUserDropdown"], { "mode": "mode"; "emailErrorLabel": "emailErrorLabel"; "inviteGuestLabel": "inviteGuestLabel"; "loadingLabel": "loadingLabel"; "placeHolder": "placeHolder"; "selectedValue": "selectedValue"; "maxTagCount": "maxTagCount"; "serverSearch": "serverSearch"; "isLoading": "isLoading"; "inviteGuest": "inviteGuest"; "listOfOption": "listOfOption"; }, { "selectedValueChange": "selectedValueChange"; "onAddGuestUserByEmail": "onAddGuestUserByEmail"; "cmacsOnSearch": "cmacsOnSearch"; }, never, never>;
}
//# sourceMappingURL=cmacs-user-dropdown.component.d.ts.map