import { ReplaySubject, Subject } from 'rxjs';
import { CmacsOptionGroupComponent } from './cmacs-option-group.component';
import { CmacsOptionComponent } from './cmacs-option.component';
import { TFilterOption } from './cmacs-option.pipe';
import * as i0 from "@angular/core";
export declare class CmacsSelectService {
    autoClearSearchValue: boolean;
    serverSearch: boolean;
    tagsOut: boolean;
    cmacsEditable: boolean;
    userDropdown: boolean;
    filterOption: TFilterOption;
    mode: 'default' | 'multiple' | 'tags' | 'tagsSingleSelect';
    maxMultipleCount: number;
    disabled: boolean;
    compareWith: (o1: any, o2: any) => boolean;
    private listOfSelectedValueWithEmit$;
    private mapOfTemplateOption$;
    private searchValueRaw$;
    private editedValueRaw$;
    listOfFilteredOption: CmacsOptionComponent[];
    private openRaw$;
    private checkRaw$;
    private open;
    clearInput$: Subject<boolean>;
    searchValue: string;
    editedValue: string;
    isShowNotFound: boolean;
    open$: import("rxjs").Observable<boolean>;
    activatedOption: CmacsOptionComponent | null;
    activatedOption$: ReplaySubject<CmacsOptionComponent>;
    listOfSelectedValue$: import("rxjs").Observable<any[]>;
    modelChange$: import("rxjs").Observable<any[]>;
    searchValue$: import("rxjs").Observable<string>;
    editedValue$: import("rxjs").Observable<string>;
    listOfSelectedValue: any[];
    listOfTemplateOption: CmacsOptionComponent[];
    listOfTagOption: CmacsOptionComponent[];
    listOfTagAndTemplateOption: CmacsOptionComponent[];
    listOfNzOptionComponent: CmacsOptionComponent[];
    listOfNzOptionGroupComponent: CmacsOptionGroupComponent[];
    addedTagOption: CmacsOptionComponent | null;
    listOfCachedSelectedOption: CmacsOptionComponent[];
    valueOrOption$: import("rxjs").Observable<[any[], {
        listOfNzOptionComponent: CmacsOptionComponent[];
        listOfNzOptionGroupComponent: CmacsOptionGroupComponent[];
    }]>;
    check$: import("rxjs").Observable<unknown>;
    clickOption(option: CmacsOptionComponent): void;
    updateListOfCachedOption(): void;
    updateListOfTagOption(): void;
    updateAddTagOption(): void;
    updateListOfFilteredOption(): void;
    clearInput(): void;
    updateListOfSelectedValue(value: any[], emit: boolean): void;
    updateActivatedOption(option: CmacsOptionComponent | null): void;
    tokenSeparate(inputValue: string, tokenSeparators: string[]): void;
    includesSeparators(str: string | string[], separators: string[]): boolean;
    splitBySeparators(str: string | string[], separators: string[]): string[];
    resetActivatedOptionIfNeeded(): void;
    updateTemplateOption(listOfNzOptionComponent: CmacsOptionComponent[], listOfNzOptionGroupComponent: CmacsOptionGroupComponent[]): void;
    updateSearchValue(value: string): void;
    updateEditedValue(value: string): void;
    updateSelectedValueByLabelList(listOfLabel: string[]): void;
    onKeyDown(e: KeyboardEvent): void;
    removeValueFormSelected(option: CmacsOptionComponent): void;
    setOpenState(value: boolean): void;
    check(): void;
    get isSingleMode(): boolean;
    get isTagsMode(): boolean;
    get isTagsSingleSelectMode(): boolean;
    get isMultipleMode(): boolean;
    get isMultipleOrTags(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<CmacsSelectService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<CmacsSelectService>;
}
//# sourceMappingURL=cmacs-select.service.d.ts.map