import { ChangeDetectorRef, ElementRef, EventEmitter, OnInit, Renderer2, TemplateRef } from '@angular/core';
import { CmacsCardTabComponent } from './cmacs-card-tab.component';
import { VgAPI } from 'ngx-videogular';
import { Source } from "../cmacs-video-player/cmacs-video-player.component";
import { DomSanitizer } from "@angular/platform-browser";
import * as i0 from "@angular/core";
export type CmacsCardType = 'file' | 'selection' | 'action' | 'team' | 'project' | 'folder' | 'measure' | 'weather' | 'big-file' | 'none' | 'video' | 'todo' | 'template';
export interface BigFile {
    title?: string;
    extension?: string;
    created_at?: string;
}
export interface Weather {
    temp?: number;
    temp_min?: number;
    temp_max?: number;
    humidity?: number;
    description?: string;
    icon?: string;
    clouds_all?: number;
    wind_speed?: number;
}
export declare class CmacsCardComponent implements OnInit {
    private cdr;
    private sanitizer;
    folderIcon: string;
    newIcon: string;
    iconspan_template: string;
    icon_template: string;
    isEditable: boolean;
    bordered: boolean;
    opened: boolean;
    editable: boolean;
    isRadio: boolean;
    loading: boolean;
    disabled: boolean;
    hoverable: boolean;
    useDefaultContent: boolean;
    sources: Source[];
    playerReady: EventEmitter<VgAPI>;
    bodyStyle: {
        [key: string]: string;
    };
    cover: TemplateRef<void>;
    body: TemplateRef<void>;
    actions: Array<TemplateRef<void>>;
    team: any;
    file: BigFile;
    project: any;
    template: any;
    projectDateLabel: string;
    todo: any;
    weather: Weather;
    celcius: boolean;
    type: string;
    cmacsType: CmacsCardType;
    cmacsIcon: string;
    cmacsIconOpenedFolder: string;
    cmacsIconClosedFolder: string;
    title: string | TemplateRef<void>;
    labelTitle: string;
    titleChange: EventEmitter<string>;
    extra: string | TemplateRef<void>;
    tab: CmacsCardTabComponent;
    ondlclickCard: EventEmitter<any>;
    open: EventEmitter<any>;
    close: EventEmitter<any>;
    selected: boolean;
    value: any;
    selectedChange: EventEmitter<boolean>;
    goToModule: EventEmitter<string>;
    todoUserAssigned: TemplateRef<void>;
    cmacsTagContents: Array<string>;
    cmacsTagsOverflow: number;
    iconToDoClick: EventEmitter<any>;
    defaultImage: string;
    constructor(cdr: ChangeDetectorRef, renderer: Renderer2, sanitizer: DomSanitizer, elementRef: ElementRef);
    openMail($event: Event): void;
    ngOnInit(): void;
    onPlayerReady(api: VgAPI): void;
    checkRadio(): void;
    onClick(event: Event): void;
    onDblClick(event: Event): void;
    tapTimeoutHandler: any;
    markForCheck(): void;
    select(event: any): void;
    handleEnter(event: KeyboardEvent, titleContainer: any, titleSpan: any): void;
    handleEdit(event: KeyboardEvent, titleSpan: any): void;
    toggleEdit(titleContainer: any): void;
    isJaponeseInitials(name: string): RegExpMatchArray;
    getInitials(name: any): any;
    getBackgroundImage(): any;
    onError(elem: any): void;
    iconsToDoClick(event: any, icon: string): void;
    goToModuleToDo(event: any, url: string): void;
    buildLabel(value: string): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<CmacsCardComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CmacsCardComponent, "cmacs-card", ["cmacsCard"], { "bordered": { "alias": "bordered"; "required": false; }; "opened": { "alias": "opened"; "required": false; }; "editable": { "alias": "editable"; "required": false; }; "isRadio": { "alias": "isRadio"; "required": false; }; "loading": { "alias": "loading"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "hoverable": { "alias": "hoverable"; "required": false; }; "useDefaultContent": { "alias": "useDefaultContent"; "required": false; }; "sources": { "alias": "sources"; "required": false; }; "bodyStyle": { "alias": "bodyStyle"; "required": false; }; "cover": { "alias": "cover"; "required": false; }; "body": { "alias": "body"; "required": false; }; "actions": { "alias": "actions"; "required": false; }; "team": { "alias": "team"; "required": false; }; "file": { "alias": "file"; "required": false; }; "project": { "alias": "project"; "required": false; }; "template": { "alias": "template"; "required": false; }; "projectDateLabel": { "alias": "projectDateLabel"; "required": false; }; "todo": { "alias": "todo"; "required": false; }; "weather": { "alias": "weather"; "required": false; }; "celcius": { "alias": "celcius"; "required": false; }; "type": { "alias": "type"; "required": false; }; "cmacsType": { "alias": "cmacsType"; "required": false; }; "cmacsIcon": { "alias": "cmacsIcon"; "required": false; }; "cmacsIconOpenedFolder": { "alias": "cmacsIconOpenedFolder"; "required": false; }; "cmacsIconClosedFolder": { "alias": "cmacsIconClosedFolder"; "required": false; }; "title": { "alias": "title"; "required": false; }; "labelTitle": { "alias": "labelTitle"; "required": false; }; "extra": { "alias": "extra"; "required": false; }; "selected": { "alias": "selected"; "required": false; }; "value": { "alias": "value"; "required": false; }; "todoUserAssigned": { "alias": "todoUserAssigned"; "required": false; }; }, { "playerReady": "playerReady"; "titleChange": "titleChange"; "ondlclickCard": "ondlclickCard"; "open": "open"; "close": "close"; "selectedChange": "selectedChange"; "goToModule": "goToModule"; "iconToDoClick": "iconToDoClick"; }, ["tab"], ["*", "[cmacs-action-panel]"], false, never>;
}
//# sourceMappingURL=cmacs-card.component.d.ts.map