import { DatePipe } from '@angular/common';
import { ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, OnDestroy, OnInit, SimpleChanges, AfterViewInit, TemplateRef } from '@angular/core';
import { NzI18nService } from 'ng-zorro-antd/i18n';
import { ExportAsService } from 'ngx-export-as';
import { GridConfig, Field } from '../core/interfaces/grid-config';
import { GridExpConfig } from '../core/interfaces/grid-exp-config';
import { ExcelService } from '../core/services/excel.service';
import { CookieService } from 'ngx-cookie-service';
import 'moment/locale/en-ie';
import { UtilService } from '../core/services/util.service';
import { NzSizeMDSType } from 'ng-zorro-antd/core/types';
import { CmacsContextMenuService } from '../cmacs-dropdown/context-menu.service';
import { CmacsInputNumberComponent } from '../cmacs-input-number/cmacs-input-number.component';
import { NzResizeEvent } from 'ng-zorro-antd/resizable';
import * as i0 from "@angular/core";
export declare class CmacsTableComponent implements OnInit, OnChanges, OnDestroy, AfterViewInit {
    private cdr;
    private i18n;
    private exportAsService;
    private cmacsContextMenuService;
    private excelService;
    private utilService;
    private datePipe;
    private cookies;
    constructor(cdr: ChangeDetectorRef, i18n: NzI18nService, exportAsService: ExportAsService, cmacsContextMenuService: CmacsContextMenuService, excelService: ExcelService, utilService: UtilService, datePipe: DatePipe, cookies: CookieService);
    locale: any;
    headerBottomStyle: {};
    private destroy$;
    size: NzSizeMDSType;
    showTotal: TemplateRef<{
        $implicit: number;
        range: [number, number];
    }>;
    pageSizeOptions: number[];
    virtualScroll: boolean;
    virtualItemSize: number;
    loadingDelay: number;
    loadingIndicator: TemplateRef<void>;
    total: number;
    title: string | TemplateRef<void>;
    footer: string | TemplateRef<void>;
    noResult: string | TemplateRef<void>;
    widthConfig: string[];
    pageIndex: number;
    pageSize: number;
    data: any[];
    config: GridConfig;
    configChange: EventEmitter<GridConfig>;
    fieldId: string;
    gridID: string;
    paginationPosition: 'top' | 'bottom' | 'both';
    scroll: {
        x?: string | null;
        y?: string | null;
    };
    nzItemRender: TemplateRef<{
        $implicit: 'page' | 'prev' | 'next';
        page: number;
    }>;
    printLandscape: boolean;
    wrapLines: boolean;
    frontPagination: boolean;
    templateMode: boolean;
    bordered: boolean;
    showPagination: boolean;
    loading: boolean;
    showSizeChanger: boolean;
    hideOnSinglePage: boolean;
    showQuickJumper: boolean;
    simple: boolean;
    checkboxSelect: boolean;
    inLineEdit: boolean;
    dataTable: boolean;
    showRate: boolean;
    hasCookies: boolean;
    exportEvent: EventEmitter<GridExpConfig>;
    buttonClick: EventEmitter<any>;
    rateChange: EventEmitter<any>;
    selectionChange: EventEmitter<any[]>;
    ondlclickRow: EventEmitter<any>;
    onclickRow: EventEmitter<any>;
    onclickFavorite: EventEmitter<any>;
    onedit: EventEmitter<any>;
    rateCount: number;
    multiSelect: boolean;
    sortChange: EventEmitter<any>;
    onresize: EventEmitter<any>;
    contextmenu: string | TemplateRef<void>;
    dropdown: any;
    selected: boolean;
    defaultSortOrder: any;
    checkboxCache: CheckboxSelect[];
    isIndeterminate: boolean;
    allChecked: boolean;
    editId: string | null;
    property: string | null;
    rowOnEdition: number;
    tapCount: number;
    lastIdxSelected: any;
    inputElement: ElementRef;
    inputNumberElement: ElementRef;
    inputNumberComponent: CmacsInputNumberComponent;
    datePickerElement: ElementRef;
    selectElement: ElementRef;
    boolElement: ElementRef;
    private _onresize$;
    onresizeobs: import("rxjs").Observable<any>;
    private _onsort$;
    onsortobs: import("rxjs").Observable<any>;
    order: number;
    clicks: number;
    contextMenu($event: MouseEvent, template: any): void;
    startEdit(id: string, property: string, event: MouseEvent): void;
    sort($event: any, fieldProperty: string): void;
    onResize(event: NzResizeEvent, col: string, field: Field): void;
    onResizeEvt({ width }: NzResizeEvent, col: string, field: Field): void;
    handleMouseDown(e: Event): void;
    focusSelect(elem: any): void;
    getHeaderMaxWidth(field: Field): string;
    childOf(node: any, ancestor: any): boolean;
    endEditMode($event: KeyboardEvent, index: number): void;
    endEditModeNgModel(index: number): void;
    getIndex(id: any): number;
    updateCheckboxCache(): void;
    getMaxWidth(): string;
    onButtonClick(field: any): void;
    onCheckboxChange($event: any, data: any): void;
    refreshCheckboxState(oninit?: boolean): void;
    checkCheckboxState(): CheckboxSelect[];
    ngModelChange(index: number): void;
    onRateChange(count: number, data: any): void;
    onFavoriteChange(isFavorite: boolean, field: Field, data: any): void;
    onRateClick(event: any): void;
    getFields(): Field[];
    onCheckboxAllChange(status: boolean): void;
    getLabel(data: any, field: Field): string;
    isSelect(field: Field): boolean;
    isReadOnly(field: Field): boolean;
    isBoolean(field: Field): boolean;
    isObject(value: any): boolean;
    isDate(field: Field): boolean;
    isString(field: Field): boolean;
    isNumber(field: Field): boolean;
    isCeldTypeDefault(field: Field): boolean;
    isCeldTypeButton(field: Field): boolean;
    isCeldTypeTag(field: Field): boolean;
    isCeldTypeTemplateRef(field: Field): boolean;
    isCeldTypeButtonFavorite(field: Field): boolean;
    isUndefined(value: any): boolean;
    isRowSelected(data: any): boolean;
    ngAfterViewInit(): void;
    getIndexCookie(): boolean;
    ngOnInit(): void;
    checkSortEvent(): void;
    checkResizeEvent(): void;
    ngOnChanges(changes: SimpleChanges): void;
    exportToPng(fileName: string): void;
    exportToExcel(fileName: string): void;
    exportToPdf(config: any): void;
    ngOnDestroy(): void;
    tapHandler($event: any, data: any): void;
    clickRow(event: MouseEvent, data: any): void;
    preventDefault($event: MouseEvent): void;
    selectRow(event: MouseEvent, data: any): void;
    removeSelection(data: any): void;
    selectMultiple(currentIdx: any): void;
    dblClickRow(data: any): void;
    transformDate(date: any): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<CmacsTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CmacsTableComponent, "cmacs-table", ["cmacsTable"], { "size": { "alias": "size"; "required": false; }; "showTotal": { "alias": "showTotal"; "required": false; }; "pageSizeOptions": { "alias": "pageSizeOptions"; "required": false; }; "virtualScroll": { "alias": "virtualScroll"; "required": false; }; "virtualItemSize": { "alias": "virtualItemSize"; "required": false; }; "loadingDelay": { "alias": "loadingDelay"; "required": false; }; "loadingIndicator": { "alias": "loadingIndicator"; "required": false; }; "total": { "alias": "total"; "required": false; }; "title": { "alias": "title"; "required": false; }; "footer": { "alias": "footer"; "required": false; }; "noResult": { "alias": "noResult"; "required": false; }; "widthConfig": { "alias": "widthConfig"; "required": false; }; "pageIndex": { "alias": "pageIndex"; "required": false; }; "pageSize": { "alias": "pageSize"; "required": false; }; "data": { "alias": "data"; "required": false; }; "config": { "alias": "config"; "required": false; }; "fieldId": { "alias": "fieldId"; "required": false; }; "gridID": { "alias": "gridID"; "required": false; }; "paginationPosition": { "alias": "paginationPosition"; "required": false; }; "scroll": { "alias": "scroll"; "required": false; }; "printLandscape": { "alias": "printLandscape"; "required": false; }; "wrapLines": { "alias": "wrapLines"; "required": false; }; "frontPagination": { "alias": "frontPagination"; "required": false; }; "templateMode": { "alias": "templateMode"; "required": false; }; "bordered": { "alias": "bordered"; "required": false; }; "showPagination": { "alias": "showPagination"; "required": false; }; "loading": { "alias": "loading"; "required": false; }; "showSizeChanger": { "alias": "showSizeChanger"; "required": false; }; "hideOnSinglePage": { "alias": "hideOnSinglePage"; "required": false; }; "showQuickJumper": { "alias": "showQuickJumper"; "required": false; }; "simple": { "alias": "simple"; "required": false; }; "checkboxSelect": { "alias": "checkboxSelect"; "required": false; }; "inLineEdit": { "alias": "inLineEdit"; "required": false; }; "dataTable": { "alias": "dataTable"; "required": false; }; "showRate": { "alias": "showRate"; "required": false; }; "hasCookies": { "alias": "hasCookies"; "required": false; }; "exportEvent": { "alias": "exportEvent"; "required": false; }; "rateCount": { "alias": "rateCount"; "required": false; }; "multiSelect": { "alias": "multiSelect"; "required": false; }; "contextmenu": { "alias": "contextmenu"; "required": false; }; }, { "configChange": "configChange"; "buttonClick": "buttonClick"; "rateChange": "rateChange"; "selectionChange": "selectionChange"; "ondlclickRow": "ondlclickRow"; "onclickRow": "onclickRow"; "onclickFavorite": "onclickFavorite"; "onedit": "onedit"; "sortChange": "sortChange"; "onresize": "onresize"; }, never, never, false, never>;
}
export interface CheckboxSelect {
    data: any;
    selected: boolean | number;
    order?: number;
}
//# sourceMappingURL=cmacs-table.component.d.ts.map