import { Direction, Directionality } from '@angular/cdk/bidi';
import { AfterContentInit, ElementRef, OnChanges, OnDestroy, OnInit, SimpleChanges, TemplateRef } from '@angular/core';
import { NzDirectionVHType, NzSafeAny, NzSizeLDSType } from 'ng-zorro-antd/core/types';
import { Observable } from 'rxjs';
import { NzListGrid } from './interface';
import { CmacsListFooterComponent, CmacsListLoadMoreDirective, CmacsListPaginationComponent } from './list-cell';
import * as i0 from "@angular/core";
export declare class CmacsListComponent implements AfterContentInit, OnChanges, OnDestroy, OnInit {
    private elementRef;
    private directionality;
    dataSource?: NzSafeAny[];
    bordered: boolean;
    grid?: NzListGrid | '';
    header?: string | TemplateRef<void>;
    footer?: string | TemplateRef<void>;
    itemLayout: NzDirectionVHType;
    classicGrid: boolean;
    renderItem: TemplateRef<void> | null;
    loading: boolean;
    loadMore: TemplateRef<void> | null;
    pagination?: TemplateRef<void>;
    size: NzSizeLDSType;
    split: boolean;
    noResult?: string | TemplateRef<void>;
    nzListFooterComponent: CmacsListFooterComponent;
    nzListPaginationComponent: CmacsListPaginationComponent;
    nzListLoadMoreDirective: CmacsListLoadMoreDirective;
    hasSomethingAfterLastItem: boolean;
    dir: Direction;
    private itemLayoutNotifySource;
    private destroy$;
    get itemLayoutNotify$(): Observable<NzDirectionVHType>;
    constructor(elementRef: ElementRef, directionality: Directionality);
    ngOnInit(): void;
    getSomethingAfterLastItem(): boolean;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    ngAfterContentInit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CmacsListComponent, [null, { optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CmacsListComponent, "cmacs-list, [cmacs-list]", ["cmacsList"], { "dataSource": { "alias": "dataSource"; "required": false; }; "bordered": { "alias": "bordered"; "required": false; }; "grid": { "alias": "grid"; "required": false; }; "header": { "alias": "header"; "required": false; }; "footer": { "alias": "footer"; "required": false; }; "itemLayout": { "alias": "itemLayout"; "required": false; }; "classicGrid": { "alias": "classicGrid"; "required": false; }; "renderItem": { "alias": "renderItem"; "required": false; }; "loading": { "alias": "loading"; "required": false; }; "loadMore": { "alias": "loadMore"; "required": false; }; "pagination": { "alias": "pagination"; "required": false; }; "size": { "alias": "size"; "required": false; }; "split": { "alias": "split"; "required": false; }; "noResult": { "alias": "noResult"; "required": false; }; }, {}, ["nzListFooterComponent", "nzListPaginationComponent", "nzListLoadMoreDirective"], ["*", "cmacs-list-header", "cmacs-list-footer, [cmacs-list-footer]", "cmacs-list-load-more, [cmacs-list-load-more]", "cmacs-list-pagination, [cmacs-list-pagination]"], false, never>;
}
//# sourceMappingURL=list.component.d.ts.map